spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace